config/routes.rb
Rails.application.routes.draw do

  resources :lists do
    resources :tasks
  end
  root :to => 'lists#index'
  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/list.rb
class List < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :list, :foreign_key => :list_id
end

app/models/user.rb
class User < ActiveRecord::Base
	authenticates_with_sorcery!

	validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
	validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
	validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

	validates :email, uniqueness: true

	has_and_belongs_to_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	before_filter :require_login

	private
	def not_authenticated
	  redirect_to login_path, alert: "Please login first"
	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @tasks = Task.where(list_id: @list.id)
  end

  # GET /lists/new
  def new

    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create

    @list = List.new(:name => params[:list][:name])
    @list.users << current_user

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @list = List.find_by(id: @task.list_id)
  end

  # GET /tasks/new
  before_filter :only_list_owner, :only => [:new, :edit, :create, :delete]
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create

    @task = Task.new(task_params.merge(list_id: params[:list_id]))

    respond_to do |format|
      if @task.save
        format.html { redirect_to [@list, @task], notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to list_task_path, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def only_list_owner
    @list = List.find_by(id: params[:list_id])
    @list.users.each do |owner|
      current_user.id == owner.id
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:stub, :description)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	skip_before_filter :require_login, except: [:destroy]
	def new
		@user = User.new
	end

	def create
		if @user = login(params[:email], params[:password])
		  redirect_back_or_to(:users, notice: 'Login successful')
		else
		  flash.now[:alert] = 'Login failed'
		  render action: 'new'
		end
	end

	def destroy
		logout
		redirect_to(:users, notice: 'Logged out!')
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @lists = @user.lists.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      format.html do
        if @user.save
          redirect_to(:lists, notice: 'User was successfully created')
          # format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to :lists, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :crypted_password, :salt)
    end

  private
  # Allow UsersController to receive form attributes
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <title>Doable</title>
  </head>
  <body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <% if current_user %>
          <li><%= link_to "Doable", user_path(current_user.id), class: "navbar-brand" %></li>
        <% else %>
          <%= link_to "Doable", lists_path, class: "navbar-brand" %>
        <% end %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if current_page?(lists_path) %>"><%= link_to "Home", lists_path %></li>
          <li class="<%= 'active' if current_page?(users_path) %>"><%= link_to "Users", users_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= link_to current_user.email, user_path(current_user.id) %></li>
            <li><%= link_to "Edit Profile", edit_user_path(current_user.id) %></li>
            <li><%= link_to "Logout", :logout, method: :post %></li>
          <% else %>
            <li><%= link_to "Register", new_user_path %></li>
            <li><%= link_to "Login", :login %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>

  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit button_name, class: "btn btn-block btn-lg btn-primary" %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1 class="text-center">Editing List</h1>

<%= render 'form', button_name: 'Update List' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Lists</h1>

<%= link_to new_list_path, class: "btn btn-default" do %>
    <i class="glyphicon glyphicon-plus"></i> New List
<% end %>

<% @lists.each do |list| %>
  <ul>
    <li>
      <h4><%= link_to list.name, list %></h4>
      <p>List owners: </p>
      <% list.users.each do |owner| %>
      <ul>
        <li><%= link_to owner.email, user_path(owner) %></li>
      </ul>

        <% if owner.id == current_user.id %>
        	<p><%= link_to 'Edit', edit_list_path(list) %>
        	<%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <% end %>
      <% end %>
    </li>
  </ul>
<% end %>

<br>

app/views/lists/new.html.erb
<h1 class="text-center">New List</h1>

<%= render 'form', button_name: 'Create List' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<h1 class="text-center">
  <%= @list.name %>
</h1>

<p class="text-center">
  <p>List owners: </p>
	<% @list.users.each do |owner| %>
		<ul>
		<li><%= link_to owner.email, user_path(owner) %></li>
		</ul>

		<% if owner.id == current_user.id %>
			<%= link_to new_list_task_path(:list_id => @list.id), :class => 'btn btn-default' do %>
		    	<i class="glyphicon glyphicon-plus"></i> New Task
			<% end %>
		<% end %>
	<% end %>
</p>

<% if @tasks.count > 0 %>
	<h3>To Do:</h3>
	<ul>
		<% @tasks.each do |task| %>
			<li><%= link_to task.stub, list_task_path(@list, task) %></li>
		<% end %>
	</ul>
<% else %>
	<h4 class="text-center user-lists">Sorry, nothing in this list yet!</h4>
<% end %>

<% @list.users.each do |owner| %>
	<% if owner.id == current_user.id %>
		<%= link_to 'Edit', edit_list_path(@list) %> |
		<%= link_to 'Back', user_path(owner) %>
	<% end %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for [@list, @task] do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!-- 
  <div class="form-group">
    <%= f.label :list_id %><br>
    <%= f.number_field :list_id, class: "form-control" %>
  </div> -->
  <div class="form-group">
    <%= f.label :stub %><br>
    <%= f.text_field :stub, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit button_name, class: "btn btn-block btn-lg btn-primary" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1 class="text-center">Editing Task</h1>

<%= render 'form', button_name: 'Update Task' %>

<%= link_to 'Show', [@list, @task] %> |
<%= link_to 'Back', list_path(@list) %>

app/views/tasks/index.html.erb
<h1>Listing Tasks</h1>

<%= link_to new_list_task_path, class: "btn btn-default" do %>
    <i class="glyphicon glyphicon-plus"></i> New Task
<% end %>

<% @tasks.each do |task| %>
    <h4><%= link_to task.stub, list_task_path(:id => task.id) %></h4>
    <p><%= task.description %></p>
    <p><%= link_to 'Edit', edit_list_task_path[:id => task.id, :list_id => @list.id] %>
    <%= link_to 'Destroy', @task, method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% end %>

<br>

app/views/tasks/new.html.erb
<h1 class="text-center">New Task</h1>

<%= render 'form', button_name: 'Create Task' %>

<%= link_to 'Back', list_tasks_path %>

app/views/tasks/show.html.erb
<p>
  <strong>List:</strong>
  <% unless @task.list_id.blank? %>
  	<%= link_to @list.name, list_path(@list) %>
  <% end %>
</p>

<p>
  <strong>Stub:</strong>
  <%= @task.stub %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<% if @list.user_id === current_user.id %>
	<%= link_to 'Edit', edit_list_task_path(@list, @task) %> |
	<%= link_to 'Back', list_path(@list) %>
<% end %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="form-group">
    <%= label_tag :email %><br />
    <%= text_field_tag(name = "email", value = nil, options = {:class => 'form-control'}) %>
  </div>
  <div class="form-group">
    <%= label_tag :password %><br />
    <%= password_field_tag(name = "password", value = nil, options = {:class => 'form-control'}) %>
  </div>
  <div class="actions">
    <%= submit_tag "Login", class: "btn btn-block btn-lg btn-primary" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1 class="text-center">Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
   <%= f.label :password %><br />
   <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
   <%= f.label :password_confirmation %><br />
   <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit button_name, class: "btn btn-block btn-lg btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="text-center">Editing User</h1>

<%= render 'form', button_name: 'Update Details' %>

<%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user| %>
    <h4><%= user.email %></h4>
    <p><%= link_to 'Show Profile', user %></p>
    <% if user.id === current_user.id %>
    	<p><%= link_to 'Edit', edit_user_path(user) %>
        <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <% end %>
<% end %>

<br>

app/views/users/new.html.erb
<h1 class="text-center">Register</h1>

<%= render 'form', button_name: 'Sign Up' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1 class="text-center"><%= @user.email %></h1>

<% if @user.id === current_user.id %>
	<%= link_to new_list_path, class: "btn btn-default" do %>
	    <i class="glyphicon glyphicon-plus"></i> New List
	<% end %>
<% end %>

<% if @lists.count > 0 %>
<ol class="user-lists">
	<% @lists.each do |list| %>
		<li>
			<h4><%= link_to list.name, list %></h4>
			<p>List owners: </p>
      		<% list.users.each do |owner| %>
	      		<ul>
	       			 <li><%= link_to owner.email, user_path(owner) %></li>
	     		 </ul>

	       		 <% if owner.id == current_user.id %>
	        		<p><%= link_to 'Edit', edit_list_path(list) %>
	        		<%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></p>
	        	 <% end %>
	       	<% end %>
   		</li>
    <% end %>
  </ol>
<% else %>
	<h4 class="text-center user-lists">Sorry, no lists to display!</h4>
<% end %>